import { useState, useEffect, useRef } from 'react';
import { motion } from 'framer-motion';
import './CounselorNote.css';

interface CounselorNoteProps {
  note: string | null;
  loading?: boolean;
  priority?: string;
  generatedBy?: string;
}

export default function CounselorNote({ note, loading = false, priority, generatedBy = 'Gemini Pro' }: CounselorNoteProps) {
  const [displayedText, setDisplayedText] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (!note) {
      setDisplayedText('');
      return;
    }

    setIsTyping(true);
    setDisplayedText('');
    let idx = 0;

    intervalRef.current = setInterval(() => {
      if (idx < note.length) {
        setDisplayedText(note.slice(0, idx + 1));
        idx++;
      } else {
        setIsTyping(false);
        if (intervalRef.current) clearInterval(intervalRef.current);
      }
    }, 18);

    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, [note]);

  return (
    <motion.div
      className="ai-insight-card"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      id="ai-counselor-note"
    >
      <div className="ai-icon">
        <span className="material-symbols-outlined icon-filled" style={{ fontSize: 22 }}>
          psychology
        </span>
        <span style={{ fontWeight: 700, fontSize: '1rem' }}>AI Diagnostic Insight</span>
        {priority && (
          <span className="counselor-priority" data-priority={priority.toLowerCase()}>
            {priority}
          </span>
        )}
      </div>

      {loading ? (
        <div className="ai-loading">
          <div className="shimmer" style={{ height: 16, width: '100%', marginBottom: 8 }} />
          <div className="shimmer" style={{ height: 16, width: '85%', marginBottom: 8 }} />
          <div className="shimmer" style={{ height: 16, width: '60%' }} />
        </div>
      ) : (
        <p className="ai-text">
          "{displayedText}"
          {isTyping && <span className="typewriter-cursor" />}
        </p>
      )}

      <div className="ai-meta">
        <span>Generated by {generatedBy}</span>
        <span> • </span>
        <span>Updated just now</span>
      </div>
    </motion.div>
  );
}
